import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Modern Crisp White Themed Foundation
        brand: {
          bg: "var(--brand-bg)",
          surface: "var(--brand-surface)",
          elevated: "var(--brand-elevated)",
          card: "var(--brand-card)",
          border: "var(--brand-border)",
          borderSubtle: "var(--brand-border-subtle)",
          borderStrong: "var(--brand-border-strong)",
          text: "var(--brand-text)",
          muted: "var(--brand-muted)",
          subtle: "var(--brand-subtle)",
        },
        navy: "var(--navy)",
        ink: "var(--ink)",
        muted: "var(--muted)",
        subtle: "var(--subtle)",
        line: "var(--line)",
        lineStrong: "var(--line-strong)",
        surface: "var(--surface)",
        surfaceAlt: "var(--bg-alt)",
        appBg: "var(--bg)",
        upay: {
          DEFAULT: "#0052FF",
          primary: "#0052FF",
          blue: "#0052FF",
          gold: "#D97706",
          amber: "#F59E0B",
          navy: "#0F172A",
          dark: "#0F172A",
          cyan: "#0284C7",
          emerald: "#10B981",
          soft: "rgba(0, 82, 255, 0.08)",
          light: "#EFF6FF",
        },
        risk: {
          critical: "#EF4444",
          criticalSoft: "rgba(239, 68, 68, 0.08)",
          high: "#F97316",
          highSoft: "rgba(249, 115, 22, 0.08)",
          medium: "#F59E0B",
          mediumSoft: "rgba(245, 158, 11, 0.08)",
          low: "#10B981",
          lowSoft: "rgba(16, 185, 129, 0.08)",
          info: "#0052FF",
          infoSoft: "rgba(0, 82, 255, 0.08)",
        },
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          '"SF Pro Display"',
          '"SF Pro"',
          '"SF Pro Icons"',
          '"Hind Siliguri"',
          '"Noto Sans Bengali"',
          "system-ui",
          '"Segoe UI"',
          '"Helvetica Neue"',
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        display: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Display"',
          '"SF Pro Text"',
          '"SF Pro"',
          '"SF Pro Icons"',
          '"Hind Siliguri"',
          '"Noto Sans Bengali"',
          "system-ui",
          '"Helvetica Neue"',
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        bangla: [
          '"Hind Siliguri"',
          '"Noto Sans Bengali"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        mono: [
          '"SF Mono"',
          "SFMono-Regular",
          "ui-monospace",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      boxShadow: {
        // Calibrated Enterprise Elevation: Subtle, calm micro-shadows that preserve border crispness
        none: "none",
        subtle: "0 1px 2px 0 rgba(15, 23, 42, 0.04)",
        sm: "0 1px 3px 0 rgba(15, 23, 42, 0.05), 0 1px 2px -1px rgba(15, 23, 42, 0.03)",
        DEFAULT: "0 1px 3px 0 rgba(15, 23, 42, 0.05), 0 1px 2px -1px rgba(15, 23, 42, 0.03)",
        md: "0 4px 6px -1px rgba(15, 23, 42, 0.06), 0 2px 4px -2px rgba(15, 23, 42, 0.04)",
        lg: "0 10px 15px -3px rgba(15, 23, 42, 0.07), 0 4px 6px -4px rgba(15, 23, 42, 0.03)",
        xl: "0 20px 25px -5px rgba(15, 23, 42, 0.08), 0 8px 10px -6px rgba(15, 23, 42, 0.04)",
        card: "0 1px 3px 0 rgba(15, 23, 42, 0.04)",
        cardHover: "0 6px 16px -2px rgba(15, 23, 42, 0.08)",
        elevated: "0 8px 24px -4px rgba(15, 23, 42, 0.08)",
        modal: "0 25px 50px -12px rgba(15, 23, 42, 0.18)",
        drawer: "-8px 0 24px -4px rgba(15, 23, 42, 0.10)",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        DEFAULT: "8px",
        md: "8px",
        lg: "10px",
        xl: "12px",
        "2xl": "16px",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(0.16, 1, 0.3, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      animation: {
        fadeIn: "fadeIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        slideInRight: "slideInRight 0.28s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        scaleUp: "scaleUp 0.22s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        stagger1: "fadeIn 0.25s cubic-bezier(0.16, 1, 0.3, 1) 0.05s forwards",
        stagger2: "fadeIn 0.25s cubic-bezier(0.16, 1, 0.3, 1) 0.12s forwards",
        stagger3: "fadeIn 0.25s cubic-bezier(0.16, 1, 0.3, 1) 0.20s forwards",
      },
    },
  },
  plugins: [],
} satisfies Config;
